example.property: "I AM IN THE DEFAULT"
spring.jpa.database: "MYSQL"
spring.jpa.show-sql: "true"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.MySQL5InnoDBDialect"
spring.datasource.driverClassName: "com.mysql.jdbc.Driver"
spring.datasource.url: "jdbc:mysql://mysql:3306/spmia_license?serverTimezone=UTC"
spring.datasource.username: "root"
spring.datasource.password: "secret"
spring.datasource.validationQuery: "SELECT 1"
